### ISSUE TITLE
Hvað skal gera ef Visa kort ekki til staðar?

### ISSUE THREAD

**Issue by HrafnkellNK** [hgop/syllabus#12]
Góðan daginn

Ég er að reyna setja upp account hjá AWS en er ekki að geta klárað það ferli þar sem $1 rukkunin sem þeir senda sem staðfesting er hafnað.
Henni er hafnað vegna þess að ég er að nota Mastercard Student debitkort Íslandsbanka sem krefjast CVS númers við öll kaup en AWS tekur ekki við CVS númeri ef þú ert með Mastercard skilst mér.

Þetta er eina kortið sem ég á og að það getur tekið uppí viku að redda nýju korti.

Hvað skal gera?

**Comment by hap2000** [comment]
Við getum boðið þeim sem geta ekki búið til vél á AWS eða eru ekki tilbúin í að nota kreditkortið sitt vél á Advanía qStack. Það hefur reyndar þann ókost að það er ekki hægt að scripta provision á þeim vélum. Þið getið þá ekki gert síðast skrefið í æfingunni fyrir dag 3. 
Sendu mér eða tölvupóst og ég mun svara þér með upplýsingum um vélina, hap@ru.is

**Comment by HrafnkellNK** [comment]
Mun notkun á Qstack valda meiri vandamálum en það leysir? þ.a.s. munu vera margir hlutir sem ég get ekki gert á Qstack og því erfiðara að leysa verkefnin? 

Ef svo er þá ætla ég frekar að reyna redda mér öðru korti.

**Comment by hap2000** [comment]
Það ætti ekki að skapa nein vandamál en það eru ákveðnar takmarkanir eins og ekki möguleiki á að scripta provision. Það væri best ef flestir gætu verið á AWS og þá erum við örugglega að gefa sömu leiðbeiningar sem virka hjá öllum en við skiljum að það eru ekki allir til í að setja fram kreditkortaupplýsingar og sumir eru ekki með kort.
