### ISSUE TITLE
Vandamál með git pull í provision scriptunni

### ISSUE THREAD

**Issue by HrafnkellNK** [hgop/syllabus#16]
Heil og sæl

Við erum fastir á því að reyna láta provision scriptuna clone-a tictactoe repo-ið yfir á instanceið svo við höfum aðgang að docker-compose.yml skránni.
Scriptan keyrir allt nema git clone. 
Það virkar að clona ef maður loggar sig inná instance-ið en ekki í gegnum scriptuna.
Við erum að láta scriptuna keyrast upp þegar instance-ið er búið til með því að adda-a scriptunni í "User data" stilinguna þegar verið er að búa til instanceið á AWS síðunni.

**Comment by stefaneg** [comment]
Rétta leiðin til að koma docker-compose.yml yfir á ec2 instance er með scp. Git clone (eða wget af github) beint inn á instance brýtur möguleikann á að endurskapa install  síðar.

scp -o StrictHostKeyChecking=no -i "YOURSECRET.pem" ./docker-compose.yaml ec2-user@${INSTANCE_PUBLIC_NAME}:~/docker-compose.yaml
