### ISSUE TITLE
Ubuntu nær ekki að tengjast Docker daemon

### ISSUE THREAD

**Issue by sandras15** [hgop/syllabus#19]
Fæ þessa villu upp og næ ekki að vinna úr henni :/

<img width="1247" alt="screen shot 2016-12-08 at 09 21 46" src="https://cloud.githubusercontent.com/assets/16047102/21020088/d14ed5d8-bd27-11e6-97d4-387c9575b007.png">

**Comment by sveinng** [comment]
Ubuntu notandinn er ekki í docker grúppunni.
Prófaðu eftirfarandi
sudo usermod -aG docker ubuntu

Þú þarft að tengjast vélinni upp á nýtt eða skrifa
newgrp docker
til að virkja breytinguna.

**Comment by sandras15** [comment]
Snilld takk! Þetta virkaði 😄
