### ISSUE TITLE
Yfirferð á kóða

### ISSUE THREAD

**Issue by arnarfs15** [hgop/syllabus#20]
Við vorum nokkrir að pæla hvort að það væri hægt ef það er ekki planið, að fara yfir strúktúrinn á kóðanum fyrir tictactoe prófanirnar og hvernig þetta hengur allt saman?
Myndi hjálpa okkur alveg rosalega mikið allavega!

**Comment by hap2000** [comment]
Varstu búin að skoða video-in þar sem Gulli fór yfir TDD og svo síðar Acceptance og Load Testing ? Þar fór hann líka aðeins yfir strúktúrinn.

**Comment by arnarfs15** [comment]
Vorum ekki búnir að ná að horfa á seinni, Kíkjum á það.
