### ISSUE TITLE
Install Docker on Ubuntu

### ISSUE THREAD

**Issue by FanneyA** [hgop/syllabus#4]
Hæhæ, 
Er að reyna að installa docker á ubuntu og er að fara eftir leiðbeiningum en fæ samt alltaf einhverjar villur hérna. Getur einhver sagt mér hvað ég er að gera vitlaust?
![image](https://cloud.githubusercontent.com/assets/16031046/20679974/05f20c8c-b595-11e6-866b-1fc9f3ae7228.png)

**Comment by sveinng** [comment]
Ég mundi segja að Ubuntu sýndarvélin þín sé ekki með netsamband.

**Comment by FanneyA** [comment]
Haha það er bara hárrétt hjá þér. Takk fyrir ;)
