### ISSUE TITLE
Tengja saman við DB

### ISSUE THREAD

**Issue by Karlk15** [hgop/syllabus#5]
Erum nokkur föst í þessu og vitum ekki hvernig við getum haldið áfram
einhver sem kannast við þetta ?

![screen shot 2016-11-29 at 6 40 31 pm](https://cloud.githubusercontent.com/assets/18688344/20723688/69963d98-b663-11e6-8923-731c59e35606.png)

**Comment by Fanneyyy** [comment]
Þessi villa kemur þegar server nær ekki tengingu við database. Getið séð það með því að stoppa database containerinn og prófa að keyra serverinn, ætti að koma sama villa :)
Þetta ætti að vera tíminn þar sem það þarf að skoða docker compose. Andri var með dæmi https://github.com/KolibriDev/intro-docker um hvernig það virkar og þurfið að skoða það eitthvað betur til að ná að tengingu á milli.

**Comment by einaralex** [comment]
Geturu gefið eitthvað hint í hvernig maður kemst áfram. Ég er alveg að missa geðheilsu yfir þessu, ég er búinn að þræða allar síður og ekkert gengur, ég fæ alltaf sömu villuna.

web_1  | (node:1) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
web_1  | Server listening on port 8080
web_1  | error fetching client from pool { Error: connect ECONNREFUSED 127.0.0.1:5432
web_1  |     at Object.exports._errnoException (util.js:1022:11)
web_1  |     at exports._exceptionWithHostPort (util.js:1045:20)
web_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
web_1  |   code: 'ECONNREFUSED',
web_1  |   errno: 'ECONNREFUSED',
web_1  |   syscall: 'connect',
web_1  |   address: '127.0.0.1',
web_1  |   port: 5432 }
web_1  | idle client error connect ECONNREFUSED 127.0.0.1:5432 Error: connect ECONNREFUSED 127.0.0.1:5432
web_1  |     at Object.exports._errnoException (util.js:1022:11)
web_1  |     at exports._exceptionWithHostPort (util.js:1045:20)
web_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
web_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 127.0.0.1:5432
web_1  | (node:1) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


docker-compose.yml:

services:
  server:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - .:/app
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/postgres
  db:
    image: 'postgres'
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"


Dockerfile:

FROM node
WORKDIR /app
ENV NODE_PATH=.
COPY ./build/ .
COPY package.json .
RUN npm install --silent
EXPOSE 8080
CMD ["node", "run.js"]

**Comment by hap2000** [comment]
Var komin lausn á þessu? Má ég loka þessu issue-i ?

**Comment by Fanneyyy** [comment]
Þessi villa kemur við tengingarvandamál, getur komið við nokkrar aðstæður en algengasta villan er búin að vera að annað hvort á eftir að búa til docker-compose.yml eða þá að hann er eitthvað vitlaus. Ættu að vera komnar mun meiri upplýsingar inná [TipsAndTricks](https://github.com/hgop/syllabus/blob/master/glossary/tipsAndTricks.md). En ef fleiri lenda í þessu er best að ná á okkur í dæmatíma eða búa til nýtt issue og setja inn Dockerfile og docker-compose file fyrir okkur að sjá :)
